---
- hosts: [kubemaster,kubenode]
  remote_user: root
  become: yes
  tasks:
  - name: Import a key from a url
    rpm_key:
      state: present
      key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

  - name: Enable EPEL Repository on CentOS 7
    yum:
      name: epel-release
      state: latest

  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: Install the 'Development tools' package group
    yum:
      name: "@Development tools"
      state: present

  - name: Install a list of packages (suitable replacement for 2.11 loop deprecation warning)
    yum:
      name:
        - htop
        - iotop
        - net-tools
        - yum-utils
      state: present

  - name: Add repository Docker
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: Enable Docker Edge repo
    ini_file:
      dest: /etc/yum.repos.d/docker-ce.repo
      section: 'docker-ce-edge'
      option: enabled
      value: '0'

  # - name: Enable Docker Test repo
  #   ini_file:
  #     dest: /etc/yum.repos.d/docer-ce.repo
  #     section: 'docker-ce-test'
  #     option: enabled
  #     value: 0

  - name: Install a list of packages docker 
    yum:
      name:
        - docker-ce
        - docker-ce-cli 
        - containerd.io
      state: present

  - name: Make sure a Docker service unit is running
    ansible.builtin.systemd:
      state: started
      name: docker
  
  - name: Make symlink Docker service unit at reboot
    ansible.builtin.systemd:
      enabled: yes
      masked: no
      name: docker

  - name: Disable SELinux
    command: setenforce 0

  - name: Disable SELinux on reboot
    selinux:
      state: disabled
  
  - name: Ensure net.bridge.bridge-nf-call-ip6tables is set to 1
    sysctl:
     name: net.bridge.bridge-nf-call-ip6tables
     value: '1'
     sysctl_set: yes
     state: present

  - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
    sysctl:
     name: net.bridge.bridge-nf-call-iptables
     value: '1'
     sysctl_set: yes
     state: present
     reload: yes
  
  - name: Add Kubernetes' YUM repository
    yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes
  
  - name: Disable SWAP Centos 7
    replace:
      path: /etc/fstab
      regexp: '^/dev/mapper/centos-swap\s*swap\s*swap\s*defaults\s*[0-9]\s*[0-9]$'
      replace: '# /dev/mapper/centos-swap swap                    swap    defaults        0 0'
